### ISSUE TITLE
underLine break when both using chinese and English

### ISSUE THREAD

**Issue by FengChendian** [zauguin/luaul#12]
Hi!
I using `\underLine` with Chinese and English Text. Then I found that line is not continuous. Line is broken between Chinese and English. I think maybe it's a bug。

![图片](https://user-images.githubusercontent.com/37545115/132969326-bbd1d71e-9b05-4f27-bc08-dfe6f9720ff2.png)

**Comment by zauguin** [comment]
Please add a small, complete example document showing the issue.

**Comment by FengChendian** [comment]
> 
> 
> Please add a small, complete example document showing the issue.

Here is a small example code:
```latex
\documentclass{ctexart}
\usepackage{lua-ul}
\begin{document}
\underLine{latex测试}
\end{document}
```

Compile the tex file using lualatex, you will find there is a blank between latex(English) and 测试(Chinese)
![图片](https://user-images.githubusercontent.com/37545115/132969772-f4cc3c1a-3b51-4afe-b382-6059614c91c3.png)

**Comment by tatsy** [comment]
Thank you very much for this useful luatex package.
Let me inform you that I encountered the same problem when using English and Japanese.

**Code**
```bibtex
\documentclass{article}
\usepackage{luatexja}
\usepackage{lua-ul}
\begin{document}
\underLine{latexあいうlatexあいうlatexあいう}
\end{document}
```

**Output**
<img width="374" alt="image" src="https://user-images.githubusercontent.com/1556493/133244047-fadc47a5-db97-4d54-88cc-4c7503938412.png">

**Comment by zauguin** [comment]
This issue has to be fixed in `luatexja`, where Hironori Kitagawa already wrote a fix for it. See https://osdn.net/projects/luatex-ja/ticket/42855 for progress on this.

**Comment by tatsy** [comment]
@zauguin Thank you for your information. I'll check it out!

**Comment by zauguin** [comment]
@FengChendian The fix should be included in the latest luatexja release. Can you confirm that this issue is resolved?

**Comment by FengChendian** [comment]
Yeah, this issue is resolved. Thanks for fix!
