### ISSUE TITLE
Strikethrough and square brackets

### ISSUE THREAD

**Issue by leomayer** [zauguin/luaul#16]
With lua-ul package version 1.7. I cannot write

```
\strikeThrough{[Note.: }
```

since the `[` is a symbol not recognized properly. Writting `{[}` or `\lbrack`  fixes the problem.  The even simpler fix is to write

```
\strikeThrough{{}[Note.: }
```

Perhaps it could be fixed by default?

**Comment by zauguin** [comment]
Thanks, this will be fixed in the next release.
