### ISSUE TITLE
0.1.2 version required

### ISSUE THREAD

**Issue by leomayer** [zauguin/luaul#5]
#4 is there a release of this package coming soon? Since I need that kind of package quite urgently and download and compile by myself is little bit tricky. Especially since I know what's the root cause of the problem is.

ETA for CTAN?

**Comment by zauguin** [comment]
> download and compile by myself is little bit tricky.

It's designed to be very simple: You can download the file [`lua-ul.dtx`](https://github.com/zauguin/luaul/raw/v0.1.2/lua-ul.dtx), locally rename it to `lua-ul.sty` and place it next to your document or in your local texmf. No need to compile/extract anything.

That being said,

> ETA for CTAN?

<24h, it's on it's way. TeX Live might take an additional day. Not sure why it wasn't updated already.
