### ISSUE TITLE
\underLine does not work with align environment

### ISSUE THREAD

**Issue by ejls** [zauguin/luaul#6]
Minimal (non-)working example:
```latex
\documentclass{article}
\usepackage{lua-ul}
\usepackage{amsmath}

\begin{document}
\[\underLine{This\ is\ underlined}\]
\begin{align}\underLine{This\ is\ not}\end{align}
\end{document}
```
Not sure if it should be considered a bug of amsmath or lua-ul…
```
$ lualatex --version
This is LuaTeX, Version 1.12.0 (TeX Live 2020 Gentoo Linux)
```
Cheers

**Comment by zauguin** [comment]
Your minimal example works for me both on TeX Live 2020, TeX Live 2021 pretest, and also on [Overleaf's TeX Live 2020](https://www.overleaf.com/project/6065d982826947b4b35f39c7). Which version of lua-ul do you have?

**Comment by ejls** [comment]
A version too old to open an issue about it (2020/03/15 v0.0.2). :/ Sorry about that, I just tested with master and it works.
